#!/bin/bash
#PBS -l nodes=32:ppn=16:xk
#PBS -l walltime=1:00:00
#PBS -N fhr_p1b_c1b
#PBS -j oe
#PBS -q normal
#PBS -A bbcc

# NOTE: lines that begin with "#PBS" are not interpreted by the shell but ARE
# used by the batch system, wheras lines that begin with multiple # signs,
# like "##PBS" are considered "commented out" by the batch system
# and have no effect.

# If you launched the job in a directory prepared for the job to run within,
# you'll want to cd to that directory
# [uncomment the following line to enable this]
# cd $PBS_O_WORKDIR

# Alternatively, the job script can create its own job-ID-unique directory
# to run within.  In that case you'll need to create and populate that
# directory with executables and perhaps inputs
# [uncomment and customize the following lines to enable this behavior]
# mkdir -p /scratch/sciteam/$USER/$PBS_JOBID
# cd /scratch/sciteam/$USER/$PBS_JOBID
# cp /scratch/job/setup/directory/* .

# To add certain modules that you do not have added via ~/.modules
#. /opt/modules/default/init/bash # NEEDED to add module function to shell
#module load craype-hugepages2M  perftools

# you can: mkdir -p /scratch/sciteam/$USER/$PBS_JOBID
# cd /scratch/sciteam/$USER/$PBS_JOBID

cd /u/sciteam/chee1/github/realm/examples/square/openmc_0_0

### launch the application
### redirecting stdin and stdout if needed
### set OMP_NUM_THREADS and the depth accordingly
### in the following there will be 1 MPI task per bulldozer FP module,
### with 2 OMP threads 1 per integer core.

### NOTE: (the "in" file must exist for input)

module load bwpy/2.0.2 
module load bwpy-mpi
module swap PrgEnv-cray/5.2.82 PrgEnv-gnu/5.2.82-gcc.4.9.3
module swap gcc gcc/5.3.0 
module unload cray-mpich
module load cray-mpich/7.5.0
module load cmake/3.9.4
module load cray-hdf5-parallel

source /projects/sciteam/bbcc/projects/openmc/openmc-parallel-python/openmc/build/myvirtualenv/bin/activate

# to debug
ulimit -c unlimited
export ATP_ENABLED=1

# no fork can help debugging
export PMI_NO_FORK=1

export OMP_NUM_THREADS=32

aprun -b -n 32 -N1 -d 16 -- bwpy-environ -- python -u openmc_input.py