language: python

install:
# We do this conditionally because it saves us some downloading if the
# version is the same.
- if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
    wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
  else
    wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  fi
- bash miniconda.sh -b -p $HOME/miniconda
- source "$HOME/miniconda/etc/profile.d/conda.sh"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
# Useful for debugging any issues with conda
- conda info -a

- conda create -n test-environment python=$TRAVIS_PYTHON_VERSION
- conda activate test-environment

- sudo apt-get install python3-sphinx

script:
  # Use Sphinx to make the html docs
  - make -C docs/ html
  # Tell GitHub not to use jekyll to compile the docs
  - touch docs/build/html/.nojekyll

# Tell Travis CI to copy the documentation to the gh-pages branch of
# your GitHub repository.
deploy:
  - provider: pypi
    user: "__token__"
    password: $PYPI_TOKEN
    skip_existing: true
    on:
      branch: docs
  - provider: pages:git
    verbose: true
    token: $GITHUB_TOKEN
    edge: true
    local_dir: ./docs/build/html/
    keep_history: true
    on:
      branch: docs
